### ISSUE TITLE
Raise ValueError

### ISSUE THREAD

**Issue by gshdong** [meetshah1995/pytorch-semseg#88]
When I run the code, it raise ValueError("Too many dimensions: %d > %d." % (ndim, ndmax)). It show that too many dimensions: 3 > 2. who can help me? Thank you!

**Comment by meetshah1995** [comment]
Can you share the entire trace and the exact command that you ran?

**Comment by gshdong** [comment]
Although I am still a beginner, I intend to run the program first. At the terminal I enter the code: python train.py --arch fcn8s --dataset ade20k. The result is the following:
Traceback (most recent call last):
  File "train.py", line 161, in <module>
    train(args)
  File "train.py", line 82, in train
    for i, (images, labels) in enumerate(trainloader):
  File "/home/gshdong/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 201, in __next__
    return self._process_next_batch(batch)
  File "/home/gshdong/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/gshdong/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 40, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/gshdong/pytorch-semseg-master/ptsemseg/loader/ade20k_loader.py", line 43, in __getitem__
    img, lbl = self.augmentations(img, lbl)
  File "/home/gshdong/pytorch-semseg-master/ptsemseg/augmentations.py", line 15, in __call__
    img, mask = Image.fromarray(img, mode='RGB'), Image.fromarray(mask, mode='L')
  File "/home/gshdong/anaconda2/lib/python2.7/site-packages/PIL/Image.py", line 2371, in fromarray
    raise ValueError("Too many dimensions: %d > %d." % (ndim, ndmax))
ValueError: Too many dimensions: 3 > 2.

**Comment by adam9500370** [comment]
https://github.com/meetshah1995/pytorch-semseg/blob/dfecf4973c702c9be4b55d5066bd4a79bcb0c1bb/ptsemseg/loader/ade20k_loader.py#L40
https://github.com/meetshah1995/pytorch-semseg/blob/dfecf4973c702c9be4b55d5066bd4a79bcb0c1bb/ptsemseg/augmentations.py#L15
Since initial lbl type is int32 and `Image.fromarray(mask, mode='L')` L mode uses 8-bit pixels rather than 32-bit.

https://github.com/meetshah1995/pytorch-semseg/blob/dfecf4973c702c9be4b55d5066bd4a79bcb0c1bb/ptsemseg/loader/ade20k_loader.py#L63
https://github.com/meetshah1995/pytorch-semseg/blob/dfecf4973c702c9be4b55d5066bd4a79bcb0c1bb/ptsemseg/loader/ade20k_loader.py#L43
Therefore, I think that `lbl = self.encode_segmap(lbl)` should be done before augmentation `img, lbl = self.augmentations(img, lbl)`.

**Comment by adam9500370** [comment]
Since initial lbl is read with 3 channels.
`Image.fromarray(mask, mode='L')` L mode can't read mask with 3 channels, therfore we got `ValueError: Too many dimensions: 3 > 2.`
If we convert lbl to 1 channel first by `lbl = self.encode_segmap(lbl)`, then we won't get this error.

**Comment by adam9500370** [comment]
Since ADE20K (http://groups.csail.mit.edu/vision/datasets/ADE20K/) has more than 150 classes,
after `encode_segmap` conversion, the maximal value of class index in ADE20K training set is 3145, which is larger than 3000.

There are 2 ways, one way is to convert class index from ADE20K to MIT SceneParse150, and the other way is to keep all the classes in ADE20K.

The first way is to convert class index from ADE20K to MIT SceneParse150, which is the same classes as `mit_sceneparsing_benchmark_loader.py`.
We can convert by index mapping between ADE20K and MIT SceneParse150,
and refer to https://github.com/CSAILVision/sceneparsing/blob/master/convertFromADE/convertFromADE.m and https://github.com/CSAILVision/sceneparsing/blob/master/convertFromADE/mapFromADE.txt.
Then we can do index mapping in `encode_segmap` by modifying the followings:
```
def load_index_mapping(self, mapFromADE_file_path='mapFromADE.txt'): # 150 classes
    mapFromADE_file = open(mapFromADE_file_path, 'r')
    index_mapping = np.empty((0, 2))
    for i, line in enumerate(mapFromADE_file.readlines()):
        index_mapping = np.vstack([index_mapping, (int(line.split()[0]), int(line.split()[1]))]) # (new_index, original_index)
    return index_mapping

def encode_segmap(self, mask):
    # Refer : http://groups.csail.mit.edu/vision/datasets/ADE20K/code/loadAde20K.m
    #         https://github.com/CSAILVision/sceneparsing/blob/master/convertFromADE/convertFromADE.m
    index_mapping = self.load_index_mapping()

    mask = mask.astype(int)
    label_mask = np.zeros((mask.shape[0], mask.shape[1]))
    label_mask = ( mask[:,:,0] // 10 ) * 256 + mask[:,:,1]

    # Map to the top 150 classes (1 ~ 150)
    label_output = np.zeros_like(label_mask)
    for l in np.unique(label_mask):
        if l in index_mapping[:, 1]:
            label_output[label_mask == l] = index_mapping[index_mapping[:, 1] == l, 0]
    return np.array(label_output, dtype=np.uint8)
```

The second way is if we want to keep original 3146 classes in ADE20K,
we may need to set `self.n_classes = 3146` and return label_mask with uint16 type in `encode_segmap`.

**Comment by adam9500370** [comment]
In addition, we can fix some minor problems in ADE20K loader.
The first problem is reading grayscale image error.
Although there are a few grayscale images in ADE20K,
refer to https://github.com/CSAILVision/semantic-segmentation-pytorch/blob/7a794dce0c58014c87c6f397292cd9af0811365f/dataset.py#L114,
`img = m.imread(img_path, mode='RGB')` we can specify mode='RGB' to read both RGB and grayscale image in RGB mode with 3 channels.

The second one is reading file list error.
https://github.com/meetshah1995/pytorch-semseg/blob/dfecf4973c702c9be4b55d5066bd4a79bcb0c1bb/ptsemseg/loader/ade20k_loader.py#L25-L27
We can replace these lines with the following lines, then we can store the correct training and validation file lists.
```
split_dict = {"training": "training", "val": "validation",}
for split_key in split_dict:
    file_list = recursive_glob(rootdir=self.root + 'images/' + split_dict[split_key] + '/', suffix='.jpg')
    self.files[split_key] = file_list
```

The third one is that resizing labels may yield fewer classes.
https://github.com/meetshah1995/pytorch-semseg/blob/dfecf4973c702c9be4b55d5066bd4a79bcb0c1bb/ptsemseg/loader/ade20k_loader.py#L68
We can replace this line with the following lines in mit_sceneparsing_benchmark_loader
https://github.com/meetshah1995/pytorch-semseg/blob/dfecf4973c702c9be4b55d5066bd4a79bcb0c1bb/ptsemseg/loader/mit_sceneparsing_benchmark_loader.py#L102-106.

**Comment by adam9500370** [comment]
After modifying the above mentioned code in both ways, I can traverse all the training data by `PYTHONPATH=. python ptsemseg/loader/ade20k_loader.py` without any error,
and I can also train with FCN and ADE20K by `python train.py --arch fcn8s --dataset ade20k` without any error.
