### ISSUE TITLE
num_channels in PSPNet SPP

### ISSUE THREAD

**Issue by qchenclaire** [meetshah1995/pytorch-semseg#94]
in your code https://github.com/meetshah1995/pytorch-semseg/blob/master/ptsemseg/models/utils.py#L365, the channel size depends on pool size but in the original version of PSPNet https://github.com/hszhao/PSPNet/blob/master/evaluation/prototxt/pspnet101_cityscapes_713.prototxt#L6723 line 6273 to 6981, the channel size is fixed over all pool sizes. Why did you modify code like that?

**Comment by adam9500370** [comment]
Hi, @qchenclaire .
You can see https://github.com/meetshah1995/pytorch-semseg/blob/dfecf4973c702c9be4b55d5066bd4a79bcb0c1bb/ptsemseg/models/pspnet.py#L80
Since `in_channels` is 2048 and  `pool_sizes` data type is list,
`len(pool_sizes)` is equal to 4 and the output channel size for all pool_conv `int(in_channels / len(pool_sizes)` is all equal to 2048/4=512.

**Comment by qchenclaire** [comment]
Oh I overlooked len(). Thank you!
